#!/usr/bin/env python3
"""Stress-test stage-2 training on the longest point-token samples."""

from __future__ import annotations

import argparse
import csv
import json
import os
import subprocess
import sys
from copy import deepcopy
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from train_hierarchical_spatiallm import (
    build_stage_configs,
    resolve_auto_stage2_model_path,
)


DATASET_NAME = "stage2_longest_point_token_stress"
WORKER_FLAG = "__run_stress_worker__"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Select the longest stage-2 point clouds under a point-token cutoff "
            "and repeatedly train on that worst-case batch."
        )
    )
    parser.add_argument(
        "config",
        type=Path,
        help="Hierarchical training config used to resolve the stage-2 settings.",
    )
    parser.add_argument(
        "--point_token_csv",
        "--point-token-csv",
        type=Path,
        required=True,
        help="CSV generated by analyze_point_tokens.py.",
    )
    parser.add_argument(
        "--dataset_json",
        "--dataset-json",
        type=Path,
        required=True,
        help="Original stage-2 training JSON represented by the point-token CSV.",
    )
    parser.add_argument(
        "--batch_size",
        "--batch-size",
        type=int,
        required=True,
        help="Per-device training batch size and number of selected worst samples.",
    )
    parser.add_argument(
        "--gas",
        type=int,
        required=True,
        help="Gradient accumulation steps.",
    )
    parser.add_argument(
        "--max_point_tokens",
        "--max-point-tokens",
        type=int,
        required=True,
        help=(
            "Select samples whose recorded CSV point_token_count is no greater "
            "than this value. This does not change the trainer's text cutoff_len."
        ),
    )
    parser.add_argument(
        "--optimizer_update_steps",
        "--optimizer-update-steps",
        type=int,
        required=True,
        help="Number of optimizer update steps to run.",
    )
    parser.add_argument(
        "--output_dir",
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Stress-test artifact directory. Defaults to a timestamped directory "
            "under saves/stress_tests."
        ),
    )
    parser.add_argument(
        "--model_name_or_path",
        "--model-name-or-path",
        default=None,
        help="Optional stage-2 model checkpoint override.",
    )
    parser.add_argument(
        "--report_to",
        "--report-to",
        default="none",
        help="Trainer reporting backend. Defaults to none for a local stress test.",
    )
    parser.add_argument(
        "--dry_run",
        "--dry-run",
        action="store_true",
        help="Create and print the stress-test artifacts without launching training.",
    )
    return parser.parse_args()


def visible_gpu_count() -> int | None:
    visible_devices = os.environ.get("CUDA_VISIBLE_DEVICES")
    if visible_devices is None:
        return None
    devices = [
        item.strip()
        for item in visible_devices.split(",")
        if item.strip() and item.strip() != "-1"
    ]
    return len(devices)


def load_point_token_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        normalized_fieldnames = [
            fieldname.strip() for fieldname in (reader.fieldnames or [])
        ]
        required = {
            "sample_index",
            "point_cloud_index",
            "point_cloud",
            "world_size_m",
            "point_count",
            "point_token_count",
            "status",
        }
        missing = required.difference(normalized_fieldnames)
        if missing:
            raise ValueError(
                f"Point-token CSV is missing columns: {sorted(missing)}. "
                f"Available columns: {normalized_fieldnames}"
            )

        rows: list[dict[str, str]] = []
        for raw_row in reader:
            rows.append(
                {
                    (key.strip() if key is not None else ""): (
                        value.strip() if value is not None else ""
                    )
                    for key, value in raw_row.items()
                }
            )
        return rows


def parse_int(row: dict[str, str], key: str) -> int:
    try:
        return int(row[key])
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"Invalid {key} value in CSV row: {row}") from exc


def parse_float(row: dict[str, str], key: str) -> float:
    try:
        return float(row[key])
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"Invalid {key} value in CSV row: {row}") from exc


def select_rows(
    rows: list[dict[str, str]],
    batch_size: int,
    max_point_tokens: int,
) -> list[dict[str, str]]:
    eligible = [
        row
        for row in rows
        if row["status"] == "ok"
        and parse_int(row, "point_token_count") <= max_point_tokens
    ]
    eligible.sort(
        key=lambda row: (
            -parse_int(row, "point_token_count"),
            -parse_int(row, "point_count"),
            parse_int(row, "sample_index"),
            parse_int(row, "point_cloud_index"),
        )
    )

    selected: list[dict[str, str]] = []
    selected_sample_indices: set[int] = set()
    for row in eligible:
        sample_index = parse_int(row, "sample_index")
        if sample_index in selected_sample_indices:
            continue
        selected.append(row)
        selected_sample_indices.add(sample_index)
        if len(selected) == batch_size:
            break

    if len(selected) < batch_size:
        raise ValueError(
            f"Only {len(selected)} unique samples have point_token_count <= "
            f"{max_point_tokens}, but batch_size={batch_size}."
        )
    return selected


def load_dataset(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as f:
        dataset = json.load(f)
    if not isinstance(dataset, list):
        raise ValueError(f"Expected a JSON list in {path}.")
    return dataset


def selected_samples(
    dataset: list[dict[str, Any]],
    selected_rows: list[dict[str, str]],
) -> list[dict[str, Any]]:
    samples: list[dict[str, Any]] = []
    for row in selected_rows:
        sample_index = parse_int(row, "sample_index")
        if sample_index < 0 or sample_index >= len(dataset):
            raise IndexError(
                f"CSV sample_index {sample_index} is outside dataset size "
                f"{len(dataset)}."
            )
        sample = deepcopy(dataset[sample_index])
        point_clouds = sample.get("point_clouds", [])
        point_cloud_index = parse_int(row, "point_cloud_index")
        if (
            not isinstance(point_clouds, list)
            or point_cloud_index >= len(point_clouds)
            or point_clouds[point_cloud_index] != row["point_cloud"]
        ):
            raise ValueError(
                "CSV and dataset JSON do not match for sample "
                f"{sample_index}: CSV point cloud={row['point_cloud']!r}, "
                f"dataset point clouds={point_clouds!r}."
            )
        samples.append(sample)
    return samples


def validate_world_size(
    selected_rows: list[dict[str, str]],
    stage2_config: dict[str, Any],
) -> float:
    csv_world_sizes = {
        parse_float(row, "world_size_m") for row in selected_rows
    }
    if len(csv_world_sizes) != 1:
        raise ValueError(
            f"Selected CSV rows contain multiple world sizes: {csv_world_sizes}"
        )
    csv_world_size = next(iter(csv_world_sizes))
    config_world_size = float(stage2_config.get("world_size", 32.0))
    if abs(csv_world_size - config_world_size) > 1e-9:
        raise ValueError(
            f"Point-token CSV uses world_size={csv_world_size:g}m, but stage 2 "
            f"uses world_size={config_world_size:g}m."
        )
    return csv_world_size


def default_output_dir(
    config: Path,
    batch_size: int,
    gas: int,
    max_point_tokens: int,
    world_size: float,
) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    world_tag = f"{world_size:g}".replace(".", "p")
    return Path("saves/stress_tests") / (
        f"{config.stem}_world{world_tag}_bs{batch_size}_gas{gas}_"
        f"maxpt{max_point_tokens}_{timestamp}"
    )


def write_json(path: Path, data: Any) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def write_yaml(path: Path, data: dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, sort_keys=False)


def write_selection_csv(
    path: Path,
    selected_rows: list[dict[str, str]],
) -> None:
    fieldnames = [
        "selection_rank",
        "sample_index",
        "point_cloud_index",
        "point_cloud",
        "resolved_path",
        "world_size_m",
        "raw_point_count",
        "cropped_point_count",
        "point_count",
        "point_token_count",
        "center_cropped",
        "rotation_angle_z_rad",
        "scaling",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for rank, row in enumerate(selected_rows, start=1):
            writer.writerow(
                {
                    key: rank if key == "selection_rank" else row.get(key, "")
                    for key in fieldnames
                }
            )


def build_stress_config(
    stage2_config: dict[str, Any],
    dataset_dir: Path,
    media_dir: Path,
    trainer_output_dir: Path,
    args: argparse.Namespace,
) -> dict[str, Any]:
    stress_config = deepcopy(stage2_config)
    stress_config.update(
        {
            "dataset": DATASET_NAME,
            "dataset_dir": str(dataset_dir),
            "media_dir": str(media_dir),
            "output_dir": str(trainer_output_dir),
            "per_device_train_batch_size": args.batch_size,
            "gradient_accumulation_steps": args.gas,
            "max_steps": args.optimizer_update_steps,
            "num_train_epochs": 1,
            "do_train": True,
            "do_eval": False,
            "eval_strategy": "no",
            "val_size": 0.0,
            "save_strategy": "no",
            "logging_steps": 1,
            "report_to": args.report_to,
            "overwrite_cache": True,
            "overwrite_output_dir": False,
            "dataloader_drop_last": True,
            "skip_memory_metrics": False,
            "run_name": (
                f"stage2_stress_bs{args.batch_size}_gas{args.gas}_"
                f"maxpt{args.max_point_tokens}"
            ),
        }
    )
    for key in (
        "eval_dataset",
        "eval_steps",
        "resume_from_checkpoint",
        "save_steps",
        "save_total_limit",
    ):
        stress_config.pop(key, None)
    if args.model_name_or_path is not None:
        stress_config["model_name_or_path"] = args.model_name_or_path
    return stress_config


def run_training_worker(config_path: Path) -> None:
    from torch.utils.data import SequentialSampler

    from spatiallm.tuner.trainer import CustomSeq2SeqTrainer, run_exp

    def get_sequential_train_sampler(
        trainer: CustomSeq2SeqTrainer,
    ) -> SequentialSampler:
        if trainer.train_dataset is None:
            raise ValueError("Stress training requires a train dataset.")
        return SequentialSampler(trainer.train_dataset)

    def skip_final_model_save(
        trainer: CustomSeq2SeqTrainer,
        output_dir: str | None = None,
        _internal_call: bool = False,
    ) -> None:
        trainer.log({"stress_test_skipped_final_model_save": 1})

    CustomSeq2SeqTrainer._get_train_sampler = get_sequential_train_sampler
    CustomSeq2SeqTrainer.save_model = skip_final_model_save
    with config_path.open("r", encoding="utf-8") as f:
        run_exp(yaml.safe_load(f))


def main() -> None:
    args = parse_args()
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be positive.")
    if args.gas <= 0:
        raise ValueError("--gas must be positive.")
    if args.max_point_tokens <= 0:
        raise ValueError("--max-point-tokens must be positive.")
    if args.optimizer_update_steps <= 0:
        raise ValueError("--optimizer-update-steps must be positive.")

    gpu_count = visible_gpu_count()
    if not args.dry_run and gpu_count != 1:
        visible = "unset" if gpu_count is None else str(gpu_count)
        raise ValueError(
            "This fixed-batch VRAM test must run with exactly one visible GPU. "
            f"Current CUDA_VISIBLE_DEVICES count: {visible}. Launch with, for "
            "example, CUDA_VISIBLE_DEVICES=5."
        )

    config_path = args.config.resolve()
    with config_path.open("r", encoding="utf-8") as f:
        hierarchical_config = yaml.safe_load(f)
    stage1_config, stage2_config = build_stage_configs(hierarchical_config)
    if args.model_name_or_path is None:
        resolve_auto_stage2_model_path(stage1_config, stage2_config)

    point_token_csv = args.point_token_csv.resolve()
    dataset_json = args.dataset_json.resolve()
    rows = load_point_token_rows(point_token_csv)
    selected_rows = select_rows(rows, args.batch_size, args.max_point_tokens)
    world_size = validate_world_size(selected_rows, stage2_config)

    dataset = load_dataset(dataset_json)
    batch_samples = selected_samples(dataset, selected_rows)
    # One epoch contains exactly `gas` full microbatches. With max_steps set,
    # Trainer repeats this epoch until the requested optimizer updates complete.
    stress_samples = [
        deepcopy(sample)
        for _ in range(args.gas)
        for sample in batch_samples
    ]

    output_dir = (
        args.output_dir.resolve()
        if args.output_dir is not None
        else default_output_dir(
            config_path,
            args.batch_size,
            args.gas,
            args.max_point_tokens,
            world_size,
        ).resolve()
    )
    if output_dir.exists():
        raise FileExistsError(
            f"Stress-test output directory already exists: {output_dir}"
        )

    dataset_dir = output_dir / "dataset"
    trainer_output_dir = output_dir / "trainer_output"
    dataset_dir.mkdir(parents=True)

    stress_dataset_path = dataset_dir / "stress_train.json"
    dataset_info_path = dataset_dir / "dataset_info.json"
    selection_path = output_dir / "selected_samples.csv"
    stress_config_path = output_dir / "stress_train.yaml"

    write_json(stress_dataset_path, stress_samples)
    write_json(
        dataset_info_path,
        {
            DATASET_NAME: {
                "file_name": stress_dataset_path.name,
                "formatting": "sharegpt",
                "columns": {
                    "messages": "conversations",
                    "point_clouds": "point_clouds",
                },
            }
        },
    )
    write_selection_csv(selection_path, selected_rows)

    original_dataset_root = Path(
        stage2_config.get("media_dir", stage2_config["dataset_dir"])
    ).resolve()
    stress_config = build_stress_config(
        stage2_config=stage2_config,
        dataset_dir=dataset_dir,
        media_dir=original_dataset_root,
        trainer_output_dir=trainer_output_dir,
        args=args,
    )
    write_yaml(stress_config_path, stress_config)

    print(f"Selected worst-case samples: {selection_path}")
    for rank, row in enumerate(selected_rows, start=1):
        print(
            f"  {rank}: tokens={parse_int(row, 'point_token_count')}, "
            f"points={parse_int(row, 'point_count')}, "
            f"sample_index={parse_int(row, 'sample_index')}, "
            f"pcd={row['point_cloud']}"
        )
    print(f"Stress dataset: {stress_dataset_path}")
    print(f"Training config: {stress_config_path}")
    print(
        f"Training plan: batch_size={args.batch_size}, gas={args.gas}, "
        f"optimizer_steps={args.optimizer_update_steps}, "
        f"world_size={world_size:g}m, "
        f"max_point_tokens={args.max_point_tokens}, "
        f"text_cutoff_len={stress_config.get('cutoff_len')}."
    )
    print(
        "Note: max_point_tokens filters the counts recorded in the CSV. Training-time "
        "random rotation/scaling can change the actual count slightly."
    )

    command = [
        sys.executable,
        str(Path(__file__).resolve()),
        WORKER_FLAG,
        str(stress_config_path),
    ]
    print(f"Command: {' '.join(command)}")
    if args.dry_run:
        return

    subprocess.run(command, check=True)


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == WORKER_FLAG:
        run_training_worker(Path(sys.argv[2]).resolve())
    else:
        main()
